version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ai-chatbot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*","-c","password_encryption=md5","-c","log_statement=all"]

volumes:
  postgres_data:
